// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrcrwxwruenstjkngfda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZyY3J3eHdydWVuc3Rqa25nZmRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NzA5NzMsImV4cCI6MjA2NzU0Njk3M30.3G9UU5AlxhYEWxQXNuZT57An0-Gq4i-zR0fQHWYtGbI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});